version: '3.7'

services:
  # Backend API
  smart-brain-server:
    container_name: backend
    # image: node:12.16.1 If we use the build: ./ it will use the Dockerfile
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-server
    environment:
      POSTGRES_URI: ${POSTGRES_URI}
      REDIS_URI: ${REDIS_URI}
    ports:
      - '3001:3001'
    volumes:
      - ./:/usr/src/smart-brain-server

  # Redis
  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'

  # Postgres DB
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    build: ./postgres
    ports:
      - '5432:5432'
